global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'customer-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['customer-service:8081']

  - job_name: 'policy-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['policy-service:8082']

  - job_name: 'claims-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['claims-service:8083']

  - job_name: 'billing-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['billing-service:8084']

  - job_name: 'risk-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['risk-service:8085']
