name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  backend-build:
    name: Build and Test Backend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [customer-service, policy-service, claims-service, billing-service, risk-service]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: |
        cd src/backend/${{ matrix.service }}
        mvn -B package --file pom.xml
    
    - name: Run Tests
      run: |
        cd src/backend/${{ matrix.service }}
        mvn -B test
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results-${{ matrix.service }}
        path: src/backend/${{ matrix.service }}/target/surefire-reports
    
    - name: Code Coverage
      run: |
        cd src/backend/${{ matrix.service }}
        mvn -B jacoco:report
    
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report-${{ matrix.service }}
        path: src/backend/${{ matrix.service }}/target/site/jacoco

  frontend-build:
    name: Build and Test Frontend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [customer-portal, admin-portal]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: src/frontend/${{ matrix.app }}/package-lock.json
    
    - name: Install Dependencies
      run: |
        cd src/frontend/${{ matrix.app }}
        npm ci
    
    - name: Run Linter
      run: |
        cd src/frontend/${{ matrix.app }}
        npm run lint
    
    - name: Run Tests
      run: |
        cd src/frontend/${{ matrix.app }}
        npm test -- --coverage
    
    - name: Build
      run: |
        cd src/frontend/${{ matrix.app }}
        npm run build
    
    - name: Upload Build
      uses: actions/upload-artifact@v3
      with:
        name: build-${{ matrix.app }}
        path: src/frontend/${{ matrix.app }}/build

  integration-tests:
    name: Run Integration Tests
    needs: [backend-build, frontend-build]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Run Integration Tests
      run: |
        # Integration test command would go here
        echo "Running integration tests"

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'Lakeside Mutual'
        path: '.'
        format: 'HTML'
        out: './reports'
    
    - name: Upload Security Report
      uses: actions/upload-artifact@v3
      with:
        name: security-report
        path: ./reports
